# Generated by Django 3.2.9 on 2021-11-14 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان ')),
                ('titletwo', models.CharField(max_length=200, verbose_name='العنوان في عنا')),
                ('descriptiontthre', models.TextField(max_length=2000, verbose_name='الوصف في عنا')),
                ('imageone', models.ImageField(upload_to='img/', verbose_name='صوره في عنا')),
                ('titleimageone', models.CharField(max_length=200, verbose_name='العنوان بجانب الصوره')),
                ('description', models.TextField(max_length=3000, verbose_name='الوصف بجانب الصوره')),
                ('imagetwo', models.ImageField(upload_to='img/', verbose_name='صوره في عنا')),
                ('titleimagetwo', models.CharField(max_length=200, verbose_name='العنوان بجانب الصوره')),
                ('descriptiontwo', models.TextField(max_length=3000, verbose_name='الوصف بجانب الصوره')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='Choose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='img/')),
                ('description', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('map', models.URLField(max_length=300)),
                ('address', models.CharField(max_length=200)),
                ('linkcontact', models.URLField(max_length=300)),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=3000)),
                ('titletwo', models.CharField(max_length=200)),
                ('titlethre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='imagelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='newbiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الموقع ')),
                ('icon', models.ImageField(upload_to='img/', verbose_name='ايقوتة الموقع ')),
                ('logo', models.ImageField(upload_to='img/', verbose_name='اللوجو')),
                ('imagew', models.ImageField(upload_to='img/', verbose_name='صورة الصفحه')),
                ('alt', models.CharField(max_length=500, verbose_name='وصف الصوره  ')),
                ('wordaboveimage1', models.CharField(max_length=200, verbose_name='كلام فوق الصوره ')),
                ('wordaboveimage2', models.CharField(max_length=200, verbose_name='كلام فوق الصوره ')),
                ('wordaboveimage3', models.CharField(max_length=200, verbose_name='كلام فوق الصوره ')),
                ('actionone', models.CharField(max_length=200, verbose_name='الزر الاول  ')),
                ('actiontwo', models.CharField(max_length=200, verbose_name='الزر الثاني ')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='ourclients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=3000)),
                ('image', models.ImageField(upload_to='img/')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='OurPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='خدمتنا')),
                ('descriptionservice', models.TextField(max_length=3000, verbose_name=',وصف الخدمات')),
                ('titleservice', models.TextField(max_length=200, verbose_name='عنوان الخدمه الاولي')),
                ('descriptionso', models.TextField(max_length=3000, verbose_name='وصف الخدمه الاولي')),
                ('titleservice2', models.TextField(max_length=200, verbose_name='2عنوان الخدمه ')),
                ('description2', models.TextField(max_length=3000, verbose_name='وصف الخدمه2')),
                ('titleservice3', models.TextField(max_length=200, verbose_name='عنوان الخدمه3')),
                ('description3', models.TextField(max_length=3000, verbose_name='وصف الخدمه3')),
                ('titleservice4', models.TextField(max_length=200, verbose_name='عنوان الخدمه4')),
                ('description4', models.TextField(max_length=3000, verbose_name='وصف الخدمه4')),
                ('titleservice5', models.TextField(max_length=200, verbose_name='عنوان الخدمه5')),
                ('description5', models.TextField(max_length=3000, verbose_name='وصف الخدمه5')),
                ('titleservice6', models.TextField(max_length=200, verbose_name='عنوان الخدمه6')),
                ('description6', models.TextField(max_length=3000, verbose_name='وصف الخدمه6')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=3000)),
                ('image', models.ImageField(upload_to='img/')),
                ('fac_link', models.URLField(max_length=300, null=True, verbose_name='facbook')),
                ('twi_link', models.URLField(max_length=300, null=True, verbose_name='twitter')),
                ('gma_link', models.URLField(max_length=300, null=True, verbose_name='gmail')),
                ('ins_link', models.URLField(max_length=300, null=True, verbose_name='instgram')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='whychooseus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(max_length=3000, verbose_name='الوصف')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='url')),
                ('choo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whychooseus_Choose', to='app.choose', verbose_name='لماذا يختارنا')),
            ],
        ),
    ]
