# Generated by Django 3.2.9 on 2021-11-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='img/')),
                ('title', models.CharField(max_length=300, null=True)),
                ('subject', models.TextField(max_length=3000, null=True)),
                ('companyname', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
