# Generated by Django 3.2.9 on 2021-11-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الموقع ')),
                ('icon', models.ImageField(upload_to='img/', verbose_name='ايقوتة الموقع ')),
                ('logo', models.ImageField(upload_to='img/', verbose_name='اللوجو')),
                ('wordaboveimage1', models.CharField(max_length=200, verbose_name='كلام فوق الصوره ')),
                ('wordaboveimage2', models.CharField(max_length=200, verbose_name='كلام فوق الصوره ')),
                ('wordaboveimage3', models.CharField(max_length=200, verbose_name='كلام فوق الصوره ')),
                ('actionone', models.CharField(max_length=200, verbose_name='الزر الاول  ')),
                ('actiontwo', models.CharField(max_length=200, verbose_name='الزر الثاني ')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='url')),
            ],
        ),
        migrations.DeleteModel(
            name='newbiz',
        ),
    ]
