# Generated by Django 3.2.9 on 2021-11-14 21:10

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211114_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
