# Generated by Django 3.2.9 on 2021-11-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_footer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelist',
            name='description',
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
