# Generated by Django 3.2.9 on 2021-11-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_imagelist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='alt',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
