# Generated by Django 3.2.9 on 2021-11-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_aboutus_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelistportfolio',
            name='alt',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
