# Generated by Django 3.2.9 on 2021-11-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_imagelistportfolio_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='gma_link',
            new_name='linked_link',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='team',
            name='alt',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
