# Generated by Django 3.2.9 on 2021-11-15 02:04

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211115_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='gmail',
            field=models.URLField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
